version: "3"

services:
  ky-app:
    # env_file:
    #   - .env
    container_name: ky-server
    restart: always
    image: hwann/qaing-be-prod:latest
    ports:
      - "8080:8080"

  # ky-mongo:
  #   container_name: ky-mongo
  #   image: mongo:7.0.5
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   command:
  #     - "--auth"
  #   volumes:
  #     - ./mongo/mongod.conf:/etc/mongod.conf
  #     - ./volume-mongo:/data/db:rw
